### ISSUE TITLE
Crate naming conventions

### ISSUE THREAD

**Issue by Pratyush** [facebookresearch/Cupcake#1]
Hi @haochenuw,

Not sure if you're aware of this, but just as a friendly heads up, in the Rust community, usually crate names are all in lowercase; this matches the naming scheme for modules. See [here](https://github.com/rust-lang/api-guidelines/discussions/29) and [here](https://rust-lang.github.io/api-guidelines/naming.html) for details. (There is some disagreement on whether to choose `kebab-case` or `snake_case`, but in both cases the name is all lowercase.)

Hence I'd like to suggest renaming the crate to `cupcake` to follow these conventions. Of course, feel free to close this issue if you'd like to keep the name as is.

**Comment by haochenuw** [comment]
Thanks for reporting this -- Actually I tried renaming the module but didn't get it to work. If you know how to rename it plz share:)

**Comment by Pratyush** [comment]
Hmm so crates.io doesn't allow changing crate names after upload; so you would have to make a new crate called `cupcake`, and change the crate name locally, and then upload it. (btw, I recommend the tool `cargo-release` to automate a lot of these release tasks)
